const userData = [
  {
    id: 0,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 2,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 3,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 4,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 5,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 6,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 7,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 8,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 9,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 10,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 11,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 12,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 13,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 14,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "false",
  },
  {
    id: 15,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 16,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 17,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 18,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 19,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
  {
    id: 20,
    username: "Amit Mandal",
    userchats: "Hi Hellow",
    usertime: "10:30 AM",
    readmsg: "true",
  },
];
export default userData;