const userStatusData = [
  {
    id: 0,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 2,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 3,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 4,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 5,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 6,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 7,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 8,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 9,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 10,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 11,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 12,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 13,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 14,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 15,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 16,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 17,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 18,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 19,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
  {
    id: 20,
    userimg: "/logo192.png",
    username: "Amit Mandal",
    userday: "Today",
    usertime: "10:30 AM",
  },
];

export default userStatusData;